name: CI/CD

on:
  push:
    branches:
      - "**"
    tags:
      - "*.*.*"
    paths:
      - .github/workflows/ci-cd.yml
      - "src/**"
      - "test/**"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          echo "Doing some CI/CD"
